name: Java CI

on:
  workflow_dispatch:  # Enables manual trigger for the workflow
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-java-build:
    uses: ./java-build.yaml  # Call the reusable workflow
    with:
      java-version: "11"  # Override the default Java version to 17
      build-command: "javac HelloWorld.java && java HelloWorld"  # Build command

