name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-java-build:
    uses: ./.github/workflows/java-build.yml  # Call the reusable workflow
    with:
      java-version: "17"  # Override the default Java version to 17
      build-command: "javac HelloWorld.java && java HelloWorld"  # Build command
