name: Java CI

# Run this workflow on any push or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11 (or any Java version you want)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Step 3: Build and run your Java application
      - name: Build with Gradle (or Maven)
        run: |
          javac HelloWorld.java
          java HelloWorld
