name: Java CI

on:
  workflow_dispatch:  # Enables manual trigger for the workflow
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-java-app:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java version
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"  # Specify the Java version you want to use

      # Run Java application (assuming the build is already done)
      - name: Run Java Application
        run: java -cp src/main/java/HelloWorld.java YourMainClass  # Adjust classpath and main class accordingly

