name: Java CI

on:
  workflow_dispatch:  # Enables manual trigger for the workflow
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-java-app:
    runs-on: ubuntu-latest

    steps:


      # Run Java application (assuming the build is already done)
      - name: Run Java Application
        run: java -cp src/main/java/HelloWorld.java YourMainClass  # Adjust classpath and main class accordingly

